In [70]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/Dataset_Facebook.csv', sep=';')

In [45]:
d2 = pd.DataFrame(df)
print(d2)

     Page total likes    Type  Category  Post Month  Post Weekday  Post Hour  \
0              139441   Photo         2          12             4          3
1              139441  Status         2          12             3         10
2              139441   Photo         3          12             3          3
3              139441   Photo         2          12             2         10
4              139441   Photo         2          12             2          3
..                ...     ...       ...         ...           ...        ...
495             85093   Photo         3           1             7          2
496             81370   Photo         2           1             5          8
497             81370   Photo         1           1             5          2
498             81370   Photo         3           1             4         11
499             81370   Photo         2           1             4          4

     Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  \
0     0.0                       2752                             5091
1     0.0                      10460                            19057
2     0.0                       2413                             4373
3     1.0                      50128                            87991
4     0.0                       7244                            13594
..    ...                        ...                              ...
495   0.0                       4684                             7536
496   0.0                       3480                             6229
497   0.0                       3778                             7216
498   0.0                       4156                             7564
499   NaN                       4188                             7292

     Lifetime Engaged Users  Lifetime Post Consumers  \
0                       178                      109
1                      1457                     1361
2                       177                      113
3                      2211                      790
4                       671                      410
..                      ...                      ...
495                     733                      708
496                     537                      508
497                     625                      572
498                     626                      574
499                     564                      524

     Lifetime Post Consumptions  \
0                           159
1                          1674
2                           154
3                          1119
4                           580
..                          ...
495                         985
496                         687
497                         795
498                         832
499                         743

     Lifetime Post Impressions by people who have liked your Page  \
0                                                 3078
1                                                11710
2                                                 2812
3                                                61027
4                                                 6228
..                                                 ...
495                                               4750
496                                               3961
497                                               4742
498                                               4534
499                                               3861

     Lifetime Post reach by people who like your Page  \
0                                                1640
1                                                6112
2                                                1503
3                                               32048
4                                                3200
..                                                ...
495                                              2876
496                                              2104
497                                              2388
498                                              2452
499                                              2200

     Lifetime People who have liked your Page and engaged with your post  \
0                                                  119
1                                                 1108
2                                                  132
3                                                 1386
4                                                  396
..                                                 ...
495                                                392
496                                                301
497                                                363
498                                                370
499                                                316

     comment    like  share  Total Interactions
0          4    79.0   17.0                 100
1          5   130.0   29.0                 164
2          0    66.0   14.0                  80
3         58  1572.0  147.0                1777
4         19   325.0   49.0                 393
..       ...     ...    ...                 ...
495        5    53.0   26.0                  84
496        0    53.0   22.0                  75
497        4    93.0   18.0                 115
498        7    91.0   38.0                 136
499        0    91.0   28.0                 119

[500 rows x 19 columns]

In [46]:
df.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [47]:
df.tail()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [48]:
d2.tail()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [49]:
d2.loc[[1,3,4,6]]

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279

In [50]:
d2.loc[1:10]

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
7,139441,Photo,3,12,7,9,1.0,13720,24137,537,232,305,19728,11056,422,0,325.0,14.0,339
8,139441,Status,2,12,7,3,0.0,11844,22538,1530,1407,1692,15220,7912,1250,0,161.0,31.0,192
9,139441,Photo,3,12,6,10,0.0,4694,8668,280,183,250,4309,2324,199,3,113.0,26.0,142
10,139441,Status,2,12,5,10,0.0,21744,42334,4258,4100,4540,37849,18952,3798,0,233.0,19.0,252

In [51]:
d2.columns

Index(['Page total likes', 'Type', 'Category', 'Post Month', 'Post Weekday',
       'Post Hour', 'Paid', 'Lifetime Post Total Reach',
       'Lifetime Post Total Impressions', 'Lifetime Engaged Users',
       'Lifetime Post Consumers', 'Lifetime Post Consumptions',
       'Lifetime Post Impressions by people who have liked your Page',
       'Lifetime Post reach by people who like your Page',
       'Lifetime People who have liked your Page and engaged with your post',
       'comment', 'like', 'share', 'Total Interactions'],
      dtype='object')

In [52]:
d2.loc[0:10, ['Post Month', 'Paid', 'comment', 'like', 'share']]

    Post Month  Paid  comment    like  share
0           12   0.0        4    79.0   17.0
1           12   0.0        5   130.0   29.0
2           12   0.0        0    66.0   14.0
3           12   1.0       58  1572.0  147.0
4           12   0.0       19   325.0   49.0
5           12   0.0        1   152.0   33.0
6           12   1.0        3   249.0   27.0
7           12   1.0        0   325.0   14.0
8           12   0.0        0   161.0   31.0
9           12   0.0        3   113.0   26.0
10          12   0.0        0   233.0   19.0

In [53]:
d2.iloc[[0,1,4,7],[2,3,5]]

   Category  Post Month  Post Hour
0         2          12          3
1         2          12         10
4         2          12          3
7         3          12          9

In [57]:
d3= d2.loc[0:5, ['Post Month', 'Paid']]
d4= d2.loc[6:8, ['Post Month', 'comment', 'like']]

In [58]:
merge_df = pd.merge(d3, d4, on='Post Month')
merge_df

    Post Month  Paid  comment   like
0           12   0.0        3  249.0
1           12   0.0        0  325.0
2           12   0.0        0  161.0
3           12   0.0        3  249.0
4           12   0.0        0  325.0
5           12   0.0        0  161.0
6           12   0.0        3  249.0
7           12   0.0        0  325.0
8           12   0.0        0  161.0
9           12   1.0        3  249.0
10          12   1.0        0  325.0
11          12   1.0        0  161.0
12          12   0.0        3  249.0
13          12   0.0        0  325.0
14          12   0.0        0  161.0
15          12   0.0        3  249.0
16          12   0.0        0  325.0
17          12   0.0        0  161.0

In [69]:
d2.sort_index(axis=1, inplace=True)
d2

,Category,Lifetime Engaged Users,Lifetime People who have liked your Page and engaged with your post,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post Total Impressions,Lifetime Post Total Reach,Lifetime Post reach by people who like your Page,Page total likes,Paid,Post Hour,Post Month,Post Weekday,Total Interactions,Type,comment,like,share
0,2,178,119,109,159,3078,5091,2752,1640,139441,0.0,3,12,4,100,Photo,4,79.0,17.0
1,2,1457,1108,1361,1674,11710,19057,10460,6112,139441,0.0,10,12,3,164,Status,5,130.0,29.0
2,3,177,132,113,154,2812,4373,2413,1503,139441,0.0,3,12,3,80,Photo,0,66.0,14.0
3,2,2211,1386,790,1119,61027,87991,50128,32048,139441,1.0,10,12,2,1777,Photo,58,1572.0,147.0
4,2,671,396,410,580,6228,13594,7244,3200,139441,0.0,3,12,2,393,Photo,19,325.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,3,733,392,708,985,4750,7536,4684,2876,85093,0.0,2,1,7,84,Photo,5,53.0,26.0
496,2,537,301,508,687,3961,6229,3480,2104,81370,0.0,8,1,5,75,Photo,0,53.0,22.0
497,1,625,363,572,795,4742,7216,3778,2388,81370,0.0,2,1,5,115,Photo,4,93.0,18.0
498,3,626,370,574,832,4534,7564,4156,2452,81370,0.0,11,1,4,136,Photo,7,91.0,38.0
499,2,564,316,524,743,3861,7292,4188,2200,81370,NaN,4,1,4,119,Photo,0,91.0,28.0

In [68]:
d2.sort_index(axis=1, ascending=False, inplace=True)
d2

,share,like,comment,Type,Total Interactions,Post Weekday,Post Month,Post Hour,Paid,Page total likes,Lifetime Post reach by people who like your Page,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post Consumptions,Lifetime Post Consumers,Lifetime People who have liked your Page and engaged with your post,Lifetime Engaged Users,Category
0,17.0,79.0,4,Photo,100,4,12,3,0.0,139441,1640,2752,5091,3078,159,109,119,178,2
1,29.0,130.0,5,Status,164,3,12,10,0.0,139441,6112,10460,19057,11710,1674,1361,1108,1457,2
2,14.0,66.0,0,Photo,80,3,12,3,0.0,139441,1503,2413,4373,2812,154,113,132,177,3
3,147.0,1572.0,58,Photo,1777,2,12,10,1.0,139441,32048,50128,87991,61027,1119,790,1386,2211,2
4,49.0,325.0,19,Photo,393,2,12,3,0.0,139441,3200,7244,13594,6228,580,410,396,671,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,26.0,53.0,5,Photo,84,7,1,2,0.0,85093,2876,4684,7536,4750,985,708,392,733,3
496,22.0,53.0,0,Photo,75,5,1,8,0.0,81370,2104,3480,6229,3961,687,508,301,537,2
497,18.0,93.0,4,Photo,115,5,1,2,0.0,81370,2388,3778,7216,4742,795,572,363,625,1
498,38.0,91.0,7,Photo,136,4,1,11,0.0,81370,2452,4156,7564,4534,832,574,370,626,3
499,28.0,91.0,0,Photo,119,4,1,4,NaN,81370,2200,4188,7292,3861,743,524,316,564,2

In [67]:
d2.sort_index(axis=0, ascending=True, inplace=True)
d2

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [63]:
#Transpose
res1 = d2.transpose()
res1

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
Page total likes,139441,139441,139441,139441,139441,139441,139441,139441,139441,139441,...,85979,85979,85979,85093,85093,85093,81370,81370,81370,81370
Type,Photo,Status,Photo,Photo,Photo,Status,Photo,Photo,Status,Photo,...,Photo,Photo,Link,Photo,Photo,Photo,Photo,Photo,Photo,Photo
Category,2,2,3,2,2,2,3,3,2,3,...,3,3,1,3,3,3,2,1,3,2
Post Month,12,12,12,12,12,12,12,12,12,12,...,1,1,1,1,1,1,1,1,1,1
Post Weekday,4,3,3,2,2,1,1,7,7,6,...,6,6,5,1,7,7,5,5,4,4
Post Hour,3,10,3,10,3,9,3,9,3,10,...,11,3,11,2,10,2,8,2,11,4
Paid,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
Lifetime Post Total Reach,2752,10460,2413,50128,7244,10472,11692,13720,11844,4694,...,5280,6184,45920,8412,5400,4684,3480,3778,4156,4188
Lifetime Post Total Impressions,5091,19057,4373,87991,13594,20849,19479,24137,22538,8668,...,8703,10228,5808,13960,9218,7536,6229,7216,7564,7292
Lifetime Engaged Users,178,1457,177,2211,671,1191,481,537,1530,280,...,951,956,753,1179,810,733,537,625,626,564
Lifetime Post Consumers,109,1361,113,790,410,1073,265,232,1407,183,...,911,901,655,1111,756,708,508,572,574,524
Lifetime Post Consumptions,159,1674,154,1119,580,1389,364,305,1692,250,...,1237,1140,763,1632,1003,985,687,795,832,743
Lifetime Post Impressions by people who have liked your Page,3078,11710,2812,61027,6228,16034,15432,19728,15220,4309,...,5757,6085,15766,8632,5654,4750,3961,4742,4534,3861
Lifetime Post reach by people who like your Page,1640,6112,1503,32048,3200,7852,9328,11056,7912,2324,...,3300,3502,10720,5348,3230,2876,2104,2388,2452,2200
Lifetime People who have liked your Page and engaged with your post,119,1108,132,1386,396,1016,379,422,1250,199,...,431,437,220,699,422,392,301,363,370,316
comment,4,5,0,58,19,1,3,0,0,3,...,1,1,0,17,10,5,0,4,7,0
like,79.0,130.0,66.0,1572.0,325.0,152.0,249.0,325.0,161.0,113.0,...,79.0,105.0,128.0,185.0,125.0,53.0,53.0,93.0,91.0,91.0
share,17.0,29.0,14.0,147.0,49.0,33.0,27.0,14.0,31.0,26.0,...,30.0,46.0,9.0,55.0,41.0,26.0,22.0,18.0,38.0,28.0
Total Interactions,100,164,80,1777,393,186,279,339,192,142,...,110,152,137,257,176,84,75,115,136,119

In [64]:
res2 = d2.shape
res2

(500, 19)

In [65]:
d2_stacked = d2.stack()
print(d2_stacked.head(15))

0  Page total likes                                                       139441
   Type                                                                    Photo
   Category                                                                    2
   Post Month                                                                 12
   Post Weekday                                                                4
   Post Hour                                                                   3
   Paid                                                                      0.0
   Lifetime Post Total Reach                                                2752
   Lifetime Post Total Impressions                                          5091
   Lifetime Engaged Users                                                    178
   Lifetime Post Consumers                                                   109
   Lifetime Post Consumptions                                                159
   Lifetime Post Impressions by people who have liked your Page             3078
   Lifetime Post reach by people who like your Page                         1640
   Lifetime People who have liked your Page and engaged with your post       119
dtype: object